project:
  type: book
  output-dir: docs

execute:
  echo: true # change to false to hide code
  
book:
  title: "The title of my most excellent thesis"
  author: "Jane Doe"
  date: "`r format(Sys.Date(), %B %d, %Y)`"
  #date-format: "MMMM YYYY"
  chapters:
    - index.qmd
    - acknowledgements.qmd         # uncomment this line to see acknowledgements in html (will appear twice in pfd)
    - foreword.qmd
    - abstract.qmd
    - introduction.qmd
    - chapter1.qmd
    - chapter2.qmd
    - chapter3.qmd
    - conclusions.qmd
    - references.qmd
  appendices:
    - app1-resources.qmd
    - app2-tools.qmd

bibliography: references.bib

format:
  # html:
  #   theme: cosmo
  pdf:
    documentclass: scrbook
    classoption: ["oneside", "open=any"]
    keep-tex: true 
    toc: true
    toc-depth: 3
    toc-title: "Table of Contents"
    lof: true
    lot: true
    number-sections: true
    number-depth: 2
    geometry:
      - inner=4cm
      - outer=2.54cm
      - top=2.54cm
      - bottom=2.54cm
      - headsep=1pt
      - headheight=1pt
      - footskip=33pt
      #- ignorehead
      #- ignorefoot
      - heightrounded
    linestretch: 2.0
    fontsize: 12pt
    mainfont: Liberation Serif
    sansfont: Liberation Serif
    papersize: a4
    template-partials:
    - "tex/before-body.tex"
    - "tex/_abstract_title.tex"
    - "tex/_titlepage.tex"
    - "tex/toc.tex"
    include-in-header:
      - text: |
          \usepackage{array} % Include the array package
          \renewcommand{\arraystretch}{2} % Adjust the value as needed
          \pagenumbering{gobble}
#          \usepackage{sectsty}
#          \usepackage{titlesec}
#         \titleformat{\chapter}[display]
#          {\Large\bfseries\centering}{}{0pt}{\fontsize{12}{15}\selectfont}
#           \titlespacing*{\chapter}{0pt}{0ex plus 1ex minus .2ex}{4.3ex plus .2ex}
#           \titlespacing*{\section}{0pt}{5.5ex plus 1ex minus .2ex}{4.3ex plus .2ex}
#           \titlespacing*{\subsection}{0pt}{5.5ex plus 1ex minus .2ex}{4.3ex plus .2ex}
#          \sectionfont{\fontsize{12}{15}\selectfont\centering}
#          \subsectionfont{\fontsize{12}{15}\selectfont\centering}
#\usepackage{setspace}\spacing{1.5}
 
editor: source

