project:
  type: book
  output-dir: .

book:
  title: A doctoral thesis title
  date: December 15, 2023
  author:
    name: Jane Doe6668
    url: http://www.janedoe.com
  downloads: [pdf]
  abstract: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam quis accumsan ante. Quisque lorem metus, varius id urna eget, lacinia dapibus sem. Etiam laoreet, quam ac mollis congue, arcu leo dictum neque, nec euismod sem enim luctus odio. Donec condimentum tortor sit amet mollis volutpat. Donec ornare libero vel velit malesuada consectetur. Vestibulum in sem non justo dignissim congue at quis erat. Integer quis erat vitae mi maximus fringilla tristique nec odio. Morbi non ipsum sapien. Vestibulum tortor est, ultricies in eros et, bibendum iaculis justo. Cras pellentesque enim quam, id pretium lacus lacinia non. Integer velit neque, ultrices a malesuada vel, imperdiet quis enim. Quisque eu facilisis urna, ut faucibus lorem. Donec mollis turpis sed arcu venenatis interdum. Nulla facilisis tortor ac scelerisque consequat."
  chapters:
    - index.qmd
    - chapters/Chapter2.qmd
    - references.qmd
  appendices:
    - appendices/AppendixA.qmd

  site-url: https://nmfs-opensci.github.io/quarto-thesis/
  repo-url: https://github.com/nmfs-opensci/quarto-thesis
  repo-actions: [edit, source, issue]
  search: true

thesis:
  # committee: 
  #   - name: Dr. Ashok Kunil
  #   - name: Dr. Ashok Kunil2
  #   - name: Dr. Ashok Kunil3
  #   - name: Dr. Ashok Kunil4
  degree-name: Doctor of Philosophy
  university: Tulane University
  department: Department of Ecology and Evolutionary Biology
  #group: Informatics Program
  faculty: School of Science and Engineering
  declaration: "frontmatter/declaration.tex"
  quotation:
    text: "Thanks to my solid academic training, today I can write hundreds of words on virtually any topic without possessing a shred of information, which is how I got a good job in journalism."
    attribution: Dave Barry
  acknowledgements: "frontmatter/acknowledgements.tex"
  abbreviations: "frontmatter/abbreviations.tex"
  symbols: "frontmatter/symbols.tex"
  dedication: "frontmatter/dedication.tex"
  logo: images/logo.png
  logo-height: "3cm"

bibliography: [example.bib]

execute:
  echo: false
  code-overflow: wrap

# urlcolor changes the url color in the body of the PDF
# linkcolor changes color of internal links (like to figures)
# toclinkcolor changes color of toc, lof and lot links
format:
  quarto-thesis-pdf: 
    urlcolor: red
    toclinkcolor: black
    toc-depth: 2

