project:
  type: book
  output-dir: docs

execute:
  echo: true # change to false to hide code
  
book:
  title: "The title of my most excellent thesis"
  author: "Jane Doe"
  date: "`r format(Sys.Date(), %B %d, %Y)`"
  #date-format: "MMMM YYYY"
  chapters:
    - acknowledgements.qmd         # uncomment this line to see acknowledgements in html (will appear twice in pfd)
    - foreword.qmd
    #- abstract.qmd
    - introduction.qmd
    - chapter1.qmd
    - chapter2.qmd
    - chapter3.qmd
    - conclusions.qmd
    - references.qmd
    - index.qmd
  appendices:
    - app1-resources.qmd
    - app2-tools.qmd

bibliography: references.bib

format:
  # html:
  #   theme: cosmo
  pdf:
    documentclass: scrreport
    classoption: ["oneside", "open=any"]
    keep-tex: true 
    toc: true
    toc-depth: 3
    toc-title: "Table of Contents"
    lof: true
    lot: true
    number-sections: false
    number-depth: 2
    geometry:
      - inner=2in
      - outer=1in
      - top=1in
      - bottom=1in
      - headsep=1pt
      - headheight=1pt
      - footskip=33pt
      - ignorehead
      - ignorefoot
      - heightrounded
    indent: true
    linestretch: 2.0 # double spacing
    fontsize: 12pt
    mainfont: TeX Gyre Termes #Alternative to Times New Roman
    sansfont: TeX Gyre Termes #Another option is Liberation Serif
    papersize: letter
    template-partials:
    - "tex/before-body.tex"
    - "tex/_abstract_title.tex"
    - "tex/_titlepage.tex"
    - "tex/toc.tex"
    #- "tex/pandoc.tex"
    # filters:
    #   - "lua/pagenumber.lua"
    include-in-header:
     - text: |
          \usepackage{fancyhdr}
          \pagestyle{fancy}
          \fancypagestyle{plain}{%
            \fancyhf{} % clear all header and footer fields
            \fancyhead[R]{\thepage} % page number in top right
            \renewcommand{\headrulewidth}{0pt}
            \renewcommand{\footrulewidth}{0pt}
          }
# include-before-body:
    #  - text: |
    #       \pagenumbering{roman}
    #       \fancypagestyle{plain}{%
    #           \fancyhf{} % clear all header and footer fields
    #           \fancyfoot[C]{\thepage} % page number in center of footer
    #       }

          
# \usepackage[manualmark]{scrlayer-scrpage}
          # \pagenumbering{gooble}
          # \rohead[]{\pagemark}      % Page number in the outer (right) header
          # \setlength{\parindent}{2em}
# \usepackage{array} % Include the array package
# \renewcommand{\arraystretch}{2} % Adjust the value as needed

# \usepackage{sectsty}
#           \usepackage{titlesec}
#           \titleformat{\chapter}{\Huge\bfseries\flushleft}{}{0pt}{\fontsize{24}{20}\selectfont}
#           \titlespacing*{\chapter}{0pt}{0ex plus 1ex minus .2ex}{6ex plus .2ex}
#           \titlespacing*{\section}{0pt}{10ex plus 1ex minus .2ex}{6ex plus .2ex}
#           \titlespacing*{\subsection}{0pt}{10ex plus 1ex minus .2ex}{6ex plus .2ex}
#           \sectionfont{\fontsize{24}{20}\selectfont\flushleft}
#           \subsectionfont{\fontsize{24}{20}\selectfont\flushleft}

    #       # \renewcommand{\headrulewidth}{0pt} % Remove header rule
editor: source

