project:
  type: book
  output-dir: docs
  
book:
  title: "The title of my most excellent thesis"
  author: "Jane Doe"
  date: '`r format(Sys.Date(), "%B %d, %Y")`'
  date-format: "MMMM YYYY"
  chapters:
    - index.qmd
#    - acknowledgements.qmd         # uncomment this line to see acknowledgements in html (will appear twice in pfd)
    - 0-abstract.qmd
    - 1-introduction.qmd
    - 2-methods.qmd
    - 3-results.qmd
    - 4-discussion.qmd
    - 5-conclusions.qmd
    - references.qmd
  appendices:
    - app1-resources.qmd
    - app2-tools.qmd

bibliography: references.bib

execute:
  echo: true # change to false to hide code

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrbook
    keep-tex: true 
    toc: false
    papersize: a4
    header-includes: |
      \usepackage{titling}
      \usepackage{datetime}
      \usepackage{geometry}
       \geometry{
       a4paper,
       total={170mm,257mm},
       left=25mm,
       top=25mm,
       }
      \setlength{\droptitle}{-4cm}
      \preauthor{
        \begin{center}
         DISSERTATION\\   % Degree
         SUBMITTED ON \MakeUppercase{\today}\\
         TO THE DEPARTMENT OF ECOLOGY AND EVOLUTIONARY BIOLOGY\\  % Department and Degree stream
         IN PARTIAL FULFILLMENT OF THE REQUIREMENTS\\
         OF THE SCHOOL OF SCIENCE AND ENGINEERING\\ %University
         OF TULANE UNIVERSITY\\
         FOR THE DEGREE\\
         OF\\
         DOCTOR OF PHILOSOPHY\\
         BY\\
         \vspace{7mm}
      }
      \postauthor{
        \end{center}
      }
       \postdate{
        \\
        \includegraphics[width=1.5in,height=1.5in]{figures/UiB-emblem500px_gray.png}\\
        \end{center}
        \newpage
        \mbox{}
        \vfill
        Cover page\\
        \emph{Beckwithia glacialis} on Snøhetta.
       }

editor: visual

